apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp 
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 6
  template:
    metadata:
      name: webapp-test-from-yaml
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp 
          image: kodekloud/webapp-color:v1